# Wikimedia Foundation Inc
route 91.198.174.0/24 via NEXTHOP;
# Wikimedia Foundation Inc
route 208.80.152.0/22 via NEXTHOP;
# Mozilla Corp
route 63.245.208.0/20 via NEXTHOP;
# Github
route 192.30.252.0/22 via NEXTHOP;
# Github
route 204.232.128.0/17 via NEXTHOP;
