# Westsaechsische Hochschule Zwickau
route 141.32.0.0/16 via NEXTHOP;
# Technische Universitaet Chemnitz
route 192.108.33.0/24 via NEXTHOP;
# Technische Universitaet Chemnitz
route 134.109.0.0/16 via NEXTHOP;
# Hochschule fuer Technik und Wirtschaft Mittweida (FH)
route 141.55.0.0/16 via NEXTHOP;
