---
- name: restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart gre-watchdog timer
  ansible.builtin.systemd:
    name: gre-watchdog.timer
    state: restarted
