log to syslog level info;
mode multitap;

mtu 1426;

method "null@l2tp";
method "null";
method "salsa2012+umac";
secure handshakes no;

offload l2tp yes;
persist interface no;

# Use "fastd --generate-key" to get secret key
include "fastd-secret.local.conf";

on verify "true";
include peers from "/tmp";

on up "
ip link set up dev $INTERFACE
batctl interface add $INTERFACE
";

on down "
batctl interface del $INTERFACE
";

peer limit 20;
